#!/bin/bash
#-------------------------------------------------------------------------------------------
# WARNING!!
# This script needs to be run inside qemu-m68k user mode linux emulation chroot environment
# 
# It installes gentoo packages into a prefix folder, which defaults to /amilux/
# Never set AMILUX variable to empty, or "/", it will damage your gentoo installation!
# The target folder needs to be an empty btrfs subvolume, which you can create:
# btrfs subvol create /amilux
#-------------------------------------------------------------------------------------------
AMILUX=/amilux/

if [ "$1" != "" ]; then
    echo "Using $1..."
    AMILUX=$1
fi

# -------------------------------
# Install base programs
# -------------------------------
USE="make-symlinks" ROOT=${AMILUX} emerge @amilux_base
mkdir -p ${AMILUX}/etc/portage/sets
cp /etc/portage/sets/amilux ${AMILUX}/etc/portage/sets/
ROOT=${AMILUX} emerge @amilux
#QMERGE=1 qmerge -K -y --root ${AMILUX} @amilux

# -------------------------------
# Create missing folders
# -------------------------------
mkdir ${AMILUX}{boot,home,root,mnt,dev,proc,sys}
mkdir ${AMILUX}var/log

# -------------------------------
# Delete unnecessary files
# -------------------------------
rm ${AMILUX}/linuxrc
rm -r ${AMILUX}etc/runlevels

# -------------------------------
# Copy over patched files
# -------------------------------
cp -af /build/src/root/* ${AMILUX}

# -------------------------------
# Last touches
# -------------------------------
passwd -R ${AMILUX} -d root
ROOT=${AMILUX} env-update

./kernel_install
